### PR TITLE
Rmcreyes/#198 prettify user commands

### LINKED ISSUE #198: Output of /rocket user commands is not very pretty
Right now all of the `/rocket user` subcommands just dump the `__str__()` representation of a User model back at the user. We should have subcommand-specific messages, with pretty output.

### PR DESCRIPTION
**Pull request by rmcreyes**
# Pull Request

## Description

**Give a brief description of your changes:**
Changed the output of the edit user command to give pretty text in Slack, similar to what was already implemented in the view user command.

## Testing

**If testing this change requires extra setup, please document it here:**

## Ticket(s)

Closes #198 

(Create a copy of that line for each Github Issue affected,
and replace "Affects" with "Closes" if merging this will close the relevant ticket.)

### CODE REVIEW

**Comment by rwblickhan** [comment]
Do you mind posting a picture of what the output looks like now, if you have one handy?

**Comment by ravenCondol** [comment]
for me i was using this lol https://api.slack.com/docs/messages/builder . it can be used to simulate output given a provided json, might be of use here

**Comment by rmcreyes** [comment]
image
  
The first message is from `/rocket user edit --major cpen`, it doesn't give any special message upon successful edit.  
The second message is from `/rocket user edit --permission admin`, it gives a special message upon error.

**Comment by rwblickhan** [comment]
Ooh fantastic, looks great, thanks!

**Pull request merged**
