### PR TITLE
docs(localdev): fix links to configuration

### LINKED ISSUE #549: Audit broken links in documentation
## Summary

I noticed a couple of dead links in the documentation while going through [the local development guide](https://rocket2.readthedocs.io/en/latest/docs/LocalDevelopmentGuide.html)

## Reproduction steps

1. Go to https://rocket2.readthedocs.io/en/latest/docs/LocalDevelopmentGuide.html
2. On section 3.1, the link for "the Slack configuration docs" is broken
3. On section 5, the link for "GitHub key configuration docs " is also broken

## Expected behavior
Links should not be broken or should be taken off the docs if not relevant

Not sure when the docs were built but could be a good time to audit some of the info there as we get started with more people getting involved.

### PR DESCRIPTION
**Pull request by bobheadxi**
Some links were incorrectly pointing to .md files, and not to the generated .html

## Ticket(s)

closes #549

### CODE REVIEW

**Comment by cheukyin699** [comment]
Doc in question: https://rocket2.readthedocs.io/en/docs-fix-links/docs/LocalDevelopmentGuide.html

**Comment by cheukyin699** [comment]
Hmmmm

image

**Comment by cheukyin699** [comment]
Do we want to change this in this PR?

**Comment by bobheadxi** [comment]
https://stackoverflow.com/questions/4743845/format-text-in-a-link-in-restructuredtext

...yikes, RST is gnarly

**Comment by bobheadxi** [comment]
Just removed the formatting in 31afe01

**Review by chuck-sys — APPROVED** [review]

**Pull request merged**
