### PR TITLE
team: naively look for emails in all users

### PR DESCRIPTION
**Pull request by bobheadxi**
# Pull Request

## Description

**Give a brief description of your changes:**

Temporary workaround for https://github.com/ubclaunchpad/rocket2/issues/493

## Testing

**If testing this change requires extra setup, please document it here:**

## Ticket(s)

Affects #

(Create a copy of that line for each Github Issue affected,
and replace "Affects" with "Closes" if merging this will close the relevant ticket.)

### CODE REVIEW

**Comment by cheukyin699** [comment]
Or something like this?

```diff
diff --git a/app/controller/command/commands/team.py b/app/controller/command/commands/team.py
index 6def3a2..347455e 100644
--- a/app/controller/command/commands/team.py
+++ b/app/controller/command/commands/team.py
@@ -702,14 +702,8 @@ class TeamCommand(Command):
         for github_id in t.members:
             users = self.facade. \
                 query(User, [('github_user_id', github_id)])
-            if len(users) != 1:
-                logging.warn(f"None/multiple users for GitHub ID {github_id}")
-
-            # For now, naiively iterate over all users, due to
-            # https://github.com/ubclaunchpad/rocket2/issues/493
-            for user in users:
-                if len(user.email) > 0:
-                    emails.append(user.email)
+            if len(users) == 1:
+                emails.append(users[0].email)
 
         # Sync permissions
         if len(emails) > 0:
```

**Comment by bobheadxi** [comment]
1. the user might not have an email set, so just appending it doesn't sound very good
2. I don't want to exclude users who have an extra account in Rocket - it should still work as if the account didn't exist

**Comment by cheukyin699** [comment]
>     2. I don't want to exclude users who have an extra account in Rocket - it should still work as if the account didn't exist

Wait people do that?

**Comment by bobheadxi** [comment]
I mean the extra accounts described in #493 seems to be a bug, not an intentional thing, so an assuming user providing an email should still expect Rocket to share their email

**Comment by cheukyin699** [comment]
Okay we making this smart.

**Review by chuck-sys — APPROVED** [review]
lgtm

**Pull request merged**
